services:
  workspace:
    container_name: java-workspace
    image: openjdk:21-jdk
    tty: true
    volumes:
      - ../:/home/vscode/workspace:cached
    ports:
      - 5050:5050

  db-container:
    container_name: mysql
    restart: unless-stopped
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      # - ./docker/mysql/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
      - ./.docker/author_api_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTHOR_API_DB_ROOT_PASSWORD:-thisIsReallyStrongPassword123}
      MYSQL_DATABASE: ${AUTHOR_API_DB_DATABASE:-dev}
      MYSQL_USER: ${AUTHOR_API_DB_USER:-mysql}
      MYSQL_PASSWORD: ${AUTHOR_API_DB_PASSWORD:-thisIsReallyStrongPassword123}
